### ISSUE TITLE
Physics is tickrate-dependant

### ISSUE THREAD

**Issue by Noiwex** [ProfessorBear/Drones-Rewrite#5]
Drones fail to fly on servers with low tickrates.

**Comment by EgrOnWire** [comment]
Can you provide us with more detailed info?

**Comment by Dexl** [comment]
Any ideas to fix this?

**Comment by Noiwex** [comment]
Setup dedicated server with -tickrate 20, drones can't get up. As tickrate gets higher, drones get better with flying.

**Comment by Dexl** [comment]
Have you any ideas to fix it without completely physics rewriting?

**Comment by EgrOnWire** [comment]
We are working towards the fix. So what about our passage to MSA? :)

**Comment by Noiwex** [comment]
What

**Comment by EgrOnWire** [comment]
Илитное местечко под солнцем метаструкта. Ниужто у меня со знанием инглиша всё так плохо.

**Comment by EgrOnWire** [comment]
nthg

**Comment by Noiwex** [comment]
MSA это фикция, да и вообще, метастракт скатился в жопу и является пристанищем для отсталых.

**Comment by EgrOnWire** [comment]
Истесна если тебя оттуда выперли за чрезмерное ЧСВ.

**Comment by Noiwex** [comment]
Уж у кого раздутое ЧСВ — так это у спецагентов MSA. Вообще, глупо обвинять
меня не зная всей подноготной.

**Comment by howtokillgarry** [comment]
Обсуждение проблемы плавно переходит в обсуждение метастракта.

**Comment by ProfessorBear** [comment]
Fixed!
